homeassistant:
  name: Home
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: 479
  unit_system: metric
  time_zone: Europe/Paris

hue: !include components/hue.yaml
logger: !include components/logger.yaml
map:
sun:
weather: !include components/weather.yaml
zone: !include zone/zones.yaml
