homeassistant:
  name: Home
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: 479
  unit_system: metric
  time_zone: Europe/Paris

default_config:

device_tracker: !include_dir_merge_list device_tracker/
hue: !include components/hue.yaml
logger: !include components/logger.yaml
map:
mqtt: !include components/mqtt.yaml
notify: !include components/notify.yaml
person: !include_dir_merge_list person/
sensor: !include_dir_merge_list sensor/
sun:
system_health:
weather: !include components/weather.yaml
xiaomi_aqara: !include components/xiaomi_aqara.yaml
zone: !include zone/zones.yaml
