homeassistant:
  name: Home
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: 479
  unit_system: metric
  time_zone: Europe/Paris

default_config:

hue: !include components/hue.yaml
logger: !include components/logger.yaml
map:
mqtt: !include components/mqtt.yaml
notify: !include components/notify.yaml
sun:
system_health:
weather: !include components/weather.yaml
xiaomi_aqara: !include components/xiaomi_aqara.yaml
zone: !include zone/zones.yaml
